version: "3.3"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always

  gofr:
    container_name: gofr
    image: intrahealth/gofr:latest
    environment: 
      - FHIR_BASE_URL=http://fhir:8080/fhir
      - REDIS_HOST=redis 
      - DB_HOST=mongo-1 
    ports:
      - "3000:3000"
    restart: always

# join core network or gofr won't see hapi
networks:
  default:
    external: true
    name: instant_default