version: '3.3'

services:
#   keycloak:
#     container_name: keycloak
#     image: jboss/keycloak:15.0.2
#     volumes:
#       - ../../../resources/keycloak/themes/gofr:/opt/jboss/keycloak/themes/gofr
#     command: ["-Djboss.http.port=8084"]
#     ports:
#       - "8084:8084"
#     environment:
#       - KEYCLOAK_USER=admin
#       - KEYCLOAK_PASSWORD=admin

  postgres:
    image: postgres:15
    container_name: gofr-postgres
    restart: always
    environment:
      - POSTGRES_DB=gofr
      - POSTGRES_USER=gofr_user
      - POSTGRES_PASSWORD=gofr_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data

  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:v5.5.2-distroless
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis
    environment:
      # add mcsd ig
      - hapi.fhir.implementationguides.mcsd.name=ihe.iti.mcsd
      - hapi.fhir.implementationguides.mcsd.version=3.5.0
      # bulk data export
      - hapi.fhir.bulk_export_enabled=true
      # subscriptions
      - hapi.fhir.subscription.resthook_enabled=true
      - hapi.fhir.subscription.websocket_enabled=true
      # partitioning
      - hapi.fhir.partitioning.enabled=true
      - hapi.fhir.partitioning.allow_references_across_partitions=true
      - hapi.fhir.partitioning.partitioning_include_in_search_hashes=false
      - hapi.fhir.enable_index_missing_fields=true
      - hapi.fhir.auto_create_placeholder_reference_targets=true
      - hapi.fhir.client_id_strategy=ANY
      - spring.datasource.url=jdbc:postgresql://postgres:5432/hapi
      - spring.datasource.username=hapi
      - spring.datasource.password=hapi
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.search.enabled=true
      - spring.jpa.properties.hibernate.search.backend.type=lucene
      - spring.jpa.properties.hibernate.search.backend.analysis.configurer=ca.uhn.fhir.jpa.search.HapiLuceneAnalysisConfigurer
      - spring.jpa.properties.hibernate.search.backend.directory.type=local-filesystem
      - spring.jpa.properties.hibernate.search.backend.directory.root=target/lucenefiles
      - spring.jpa.properties.hibernate.search.backend.lucene_version=lucene_current
    volumes:
      - hapi-data:/data/hapi

  gofr:
    container_name: gofr
    image: intrahealth/gofr:latest
    depends_on:
      - fhir
      - postgres
    environment:
      # use gofr for authn/authz which is default
      # - app__idp=keycloak
      - DATABASE_URL=postgres://gofr_user:gofr_pass@postgres:5432/gofr
      - mCSD__server__protocal=http
      - mCSD__server__host=fhir
      - mCSD__server__port=8080
      - mCSD__server__basePath=fhir
      - app__site__path=/src/gofr-backend/docker-site
      - app__core__path=/src/gofr-backend/lib
      - app__installed=${false}
      - app__idp=gofr
      #- keycloak__baseURL=http://keycloak:8084/auth
      - REDIS_HOST=redis
      - JWT_SECRET=supersecreto
      - DEFAULT_ADMIN_USERNAME=admin
      - DEFAULT_ADMIN_PASSWORD=changeme
    ports:
      - "4000:4000"
    restart: always


networks:
# set app-wide default network
  default:
    name: demo


volumes:
  postgres_data:
  redis-data:
  hapi-data:
