version: '3.7'

services:

  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak

  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:15
    restart: always
    depends_on:
      - postgresql
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_MANAGEMENT_USER=gofr@keycloak.org
      - KEYCLOAK_MANAGEMENT_PASSWORD=gofr
      
  redis:
    container_name: redis-gofr
    image: docker.io/redis
    ports:
      - "6379:6379"
    restart: always

  fhir:
    container_name: hapi-fhir
    image: docker.io/hapiproject/hapi:v5.6.0-distroless
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - redis
    environment:
      # add mcsd ig
      - hapi.fhir.implementationguides.mcsd.name=ihe.iti.mcsd
      - hapi.fhir.implementationguides.mcsd.version=3.5.0
      # bulk data export
      - hapi.fhir.bulk_export_enabled=true
      # subscriptions
      - hapi.fhir.subscription.resthook_enabled=true
      - hapi.fhir.subscription.websocket_enabled=true
      # partitioning
      - hapi.fhir.partitioning.enabled=true
      - hapi.fhir.partitioning.allow_references_across_partitions=false
      - hapi.fhir.partitioning.partitioning_include_in_search_hashes=false
      - hapi.fhir.enable_index_missing_fields=true
      - hapi.fhir.auto_create_placeholder_reference_targets=true
      - hapi.fhir.client_id_strategy=ANY
      - spring.jpa.properties.hibernate.search.enabled=true
      - spring.jpa.properties.hibernate.search.backend.type=lucene
      - spring.jpa.properties.hibernate.search.backend.analysis.configurer=ca.uhn.fhir.jpa.search.HapiLuceneAnalysisConfigurer
      - spring.jpa.properties.hibernate.search.backend.directory.type=local-filesystem
      - spring.jpa.properties.hibernate.search.backend.directory.root=target/lucenefiles
      - spring.jpa.properties.hibernate.search.backend.lucene_version=lucene_current

  hapi-cli:
    container_name: hapi-cli
    image: docker.io/intrahealth/hapi-fhir-cli:latest
    depends_on:
      - fhir
    command: /bin/sh -c "/upload-definitions.sh -p 8080 -h fhir"

  gofr:
    container_name: gofr
    image: docker.io/intrahealth/gofr:latest
    environment:
      - app__idp=keycloak
      - mCSD__server__protocal=http
      - mCSD__server__host=fhir
      - mCSD__server__port=8080
      - mCSD__server__basePath=fhir
      - REDIS_HOST=redis
    ports:
      - "4000:4000"
    restart: always

# join core network
# networks:
#   default:
#     external: true
#     name: instant_default
