---
- name: HAPI FHIR Server
  hosts: all
  remote_user: "{{ user }}"
  # become: true
  tags: prep

  
  vars_prompt:

    - name: "user"
      prompt: "Please enter the username (with sudo)"
      private: no

    - name: "pgpass"
      prompt: "Please provide the password for the hapi postgres user in plain text (it will be md5-hashed)"
      private: no



  tasks:

  - name: hapi folder exists
    stat:
      path: $HOME/hapi-fhir-jpaserver-starter
    register: stat_result2


  - name: git clone repo hapi-jpa-server-starter
    git:
      repo: 'https://github.com/hapifhir/hapi-fhir-jpaserver-starter.git'
      dest: /home/{{ user }}/hapi-fhir-jpaserver-starter
      clone: yes
      # note that this blows away any existing changes to application.yaml
      force: yes
      # update: yes
      # version: image/v5.5.2
    when: stat_result2.stat.exists == False


  - name: git pull if updated
    git:
      repo: 'https://github.com/hapifhir/hapi-fhir-jpaserver-starter.git'
      dest: /home/{{ user }}/hapi-fhir-jpaserver-starter
      update: yes
      force: yes


  - name: git checkout image/v5.5.2
    shell: git checkout image/v5.5.2
    args:
      chdir: /home/{{ user }}/hapi-fhir-jpaserver-starter


  - name: install application.yaml template for hapi jpa Server
    template:
      src: 552-application.yaml
      dest: /home/{{ user }}/hapi-fhir-jpaserver-starter/src/main/resources/application.yaml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
      force: yes


  - name: mvn --no-transfer-progress --batch-mode package
    shell: mvn --no-transfer-progress --batch-mode package -DskipTests
    args:
      chdir: /home/{{ user }}/hapi-fhir-jpaserver-starter
    environment:
      MAVEN_OPTS: -Xmx2048m


# stop tomcat
  - name: stop tomcat9
    service: 
      name: tomcat9.service
      state: stopped
      enabled: yes
    become: true


# move default ROOT into ROOT-Closed
  - name: move default ROOT into ROOT-Closed
    shell: mv /var/lib/tomcat9/webapps/ROOT /var/lib/tomcat9/webapps/ROOT-Closed
    become: true
    # this works once, then fails
    ignore_errors: yes


# move package into /var/lib/tomcat9/webapps/
  - name: move war file to /var/lib/tomcat9/webapps/
    shell: cp ROOT.war /var/lib/tomcat9/webapps/
    args:
      chdir: /home/{{ user }}/hapi-fhir-jpaserver-starter/target/
    become: true


  # - name: Create a tomcast9 override directory if it does not exist
  #   ansible.builtin.file:
  #     path: /etc/systemd/system/tomcat9.service.d
  #     state: directory
  #     owner: root
  #     group: root
  #     mode: '0755'


# stop tomcat
  # - name: stop tomcat9
  #   service: 
  #     name: tomcat9.service
  #     state: stopped
  #     enabled: yes



# todo move over tomcat9 override file for env vars
  # - name: Copy tomcat9 override file
  #   ansible.builtin.copy:
  #     # if src is on remote
  #     # src: /home/{{ user }}/gofr/packaging/ansible/tomcat9_override.conf
  #     # use file on controller
  #     src: tomcat9_override.conf
  #     dest: /etc/systemd/system/tomcat9.service.d/tomcat9_override.conf
  #     # copy from remote clone, comment out to use local version
  #     # remote_src: yes
  #     owner: root
  #     group: root
  #     mode: '0755'



# kick tomcat
  - name: kick tomcat9
    service: 
      name: tomcat9.service
      state: started
      enabled: yes
    become: true


# pause to let tomcat start and then check status
  - pause:
      seconds: 10

# status
  - name: status
    command: systemctl status tomcat9.service
    register: status


  - debug:
      msg: "{{ status.stdout_lines }}"


  - name: Gather facts on listening ports
    listen_ports_facts:


  - name: List TCP ports
    debug:
      msg: "{{ ansible_facts.tcp_listen  | map(attribute='port') | sort | list }}"
