---
- name: Install facility reconciliation tool standalone
  hosts: all
  remote_user: "{{ user }}"
  tags: install


  vars_prompt:
    - name: "user"
      prompt: "Please enter the username (with sudo)"
      private: no

  tasks:


  - name: Install/update packages based on package.json for gui
    npm:
      path: $HOME/facility-recon/facility-recon-gui
      state: latest


# use static ip since site is static and vars cannot be dynamically interpreted
  - replace:
      path: $HOME/facility-recon/facility-recon-gui/src/App.vue
      regexp: 'process.env.BACKEND_SERVER'
      replace: '"{{ ansible_default_ipv4.address }}"'
      backup: no


  - replace:
      path: $HOME/facility-recon/facility-recon-gui/src/components/DataSources/FacilityReconDataSourcePair.vue
      regexp: 'process.env.BACKEND_SERVER'
      replace: '"{{ ansible_default_ipv4.address }}"'
      backup: no


  - replace:
      path: $HOME/facility-recon/facility-recon-gui/src/components/DataSync/dataSourcesMixin.js
      regexp: 'process.env.BACKEND_SERVER'
      replace: '"{{ ansible_default_ipv4.address }}"'
      backup: no


  - replace:
      path: $HOME/facility-recon/facility-recon-gui/src/components/DataSync/FacilityReconDataSync.vue
      regexp: 'process.env.BACKEND_SERVER'
      replace: '"{{ ansible_default_ipv4.address }}"'
      backup: no


  - replace:
      path: $HOME/facility-recon/facility-recon-gui/src/components/DataSync/FacilityReconUpload.vue
      regexp: 'process.env.BACKEND_SERVER'
      replace: '"{{ ansible_default_ipv4.address }}"'
      backup: no


  - replace:
      path: $HOME/facility-recon/facility-recon-gui/src/components/FacilityReconDbAdmin.vue
      regexp: 'process.env.BACKEND_SERVER'
      replace: '"{{ ansible_default_ipv4.address }}"'
      backup: no


  - replace:
      path: $HOME/facility-recon/facility-recon-gui/src/components/FacilityReconScores.vue
      regexp: 'process.env.BACKEND_SERVER'
      replace: '"{{ ansible_default_ipv4.address }}"'
      backup: no


  - replace:
      path: $HOME/facility-recon/facility-recon-gui/src/components/FacilityReconView.vue
      regexp: 'process.env.BACKEND_SERVER'
      replace: '"{{ ansible_default_ipv4.address }}"'
      backup: no


  - replace:
      path: $HOME/facility-recon/facility-recon-gui/src/components/FacilityRecoStatus.vue
      regexp: 'process.env.BACKEND_SERVER'
      replace: '"{{ ansible_default_ipv4.address | quote }}"'
      backup: no


  - replace:
      path: $HOME/facility-recon/facility-recon-gui/src/mixins/scoresMixin.js
      regexp: 'process.env.BACKEND_SERVER'
      replace: '"{{ ansible_default_ipv4.address | quote }}"'
      backup: no



  # need env to build static files correctly: BACKEND_SERVER={{ ansible_default_ipv4.address }}
  # if for dhis on a separate system this needs to be reconfigured because it assumes the same server
  - name: Build static site for facility-recon-gui
    shell: cd $HOME/facility-recon/facility-recon-gui && node build/build.js


  - name: copy static web app files generated by npm run build for dhis2 app
    shell: cp -r $HOME/facility-recon/facility-recon-gui/dist/* $HOME/facility-recon/dhis2App/
    register: helloagain2


  - debug: msg="{{ helloagain2.stdout_lines }}"


  - name: remove previous dhis2 app if it exists
    file:
      path: $HOME/facility-recon/dhis2App/GOFR.zip
      state: absent


  - name: create a zip archive of dhis2App as GOFR.zip
    archive:
      path: $HOME/facility-recon/dhis2App/*
      dest: $HOME/facility-recon/dhis2App/GOFR.zip
      format: zip


  - name: Install http-server node.js package globally.
    npm:
      name: http-server
      global: yes
    # need sudo for global packages 
    become: true


  - name: Install systemd template for gui service (ubuntu)
    template:
      src: facility-recon-gui.service.j2
      dest: /etc/systemd/system/facility-recon-gui.service
      mode: 644
      force: yes
    vars:
      executable: "/usr/bin/http-server"
    when: ansible_distribution == 'Ubuntu'
    become: true


  - name: Install systemd template for gui service (centos)
    template:
      src: facility-recon-gui.service.j2
      dest: /etc/systemd/system/facility-recon-gui.service
      mode: 644
      force: yes
    vars:
      executable: "/usr/bin/http-server"
    when: ansible_distribution == 'CentOS'
    become: true


  - name: run gui
    service: 
      name: facility-recon-gui.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    become: true
